### ISSUE TITLE
ENH: Github cheat sheet

### ISSUE THREAD

**Issue by Eric89GXL** [LABSN/expyfun#158]
@deanp3 can you put one together based on what you're learning? Something to help @akclee do his PR would be excellent. It could go in the `expyfun` wiki, we should add a section called "development".

**Comment by Eric89GXL** [comment]
@deanp3 still interested in doing this? If not I think I saw @lkishline had one on the wall.

**Comment by lkishline** [comment]
@deanp3 if you want, I can do this tomorrow. I have a bunch of cheat sheets all over the place that I can put together. 
Maybe we could also have a cheat sheet for things like WDYT(what do you think?) and SGTM (sounds good to me?)...bunch of EAU's (elitist acronym users). ;)

**Comment by deanp3** [comment]
I am pretty out of the loop, I don't think I would be good for this. 
Dean

**Comment by Eric89GXL** [comment]
don't forget YAGNI, DRY, and LGTM

**Comment by lkishline** [comment]
No problem, it is beneficial for me to do it at the moment. Feel free to pitch in if you want to though.
LGTM - looks good to me?
DRY - don't repeat yourself?
YAGNI - sounds like some kind of sushi...

**Comment by Eric89GXL** [comment]
DRY (programming principle) and LGTM are correct
[YAGNI] (http://lmgtfy.com/?q=YAGNI&l=1)

**Comment by drammock** [comment]
This cheat sheet might be the perfect opportunity to learn about tables in
markdown too. Just sayin'.

**Comment by lkishline** [comment]
Mmmm markdown tables, sounds lovely. I will give it a go Dan.

**Comment by drammock** [comment]
@lkishline did you ever get started on this?  Is there a work-in-progress that someone else should work from?  @Eric89GXL WDYT about shoehorning this into a CONTRIBUTING.md file?

**Comment by Eric89GXL** [comment]
That's fine with me

**Comment by lkishline** [comment]
Whoops, I remember doing this a while ago and then never did anything with
it. I will search for the file tonight or early tomorrow and give what I
have.

**Comment by kambysese** [comment]
EAU is by far my favorite acronym of the bunch :+1:  also doubles for [European Assoc of Urology](https://www.acronymfinder.com/EAU.html)

**Comment by Eric89GXL** [comment]
I think this is outside our scope, hopefully someone else makes one
