### ISSUE TITLE
ENH: describe HRIR/HRTF spec in documentation

### ISSUE THREAD

**Issue by rkmaddox** [LABSN/expyfun#175]
Trying to add a new set of HRIRs (that should have better low end), but it is not super clear what the file formats should be. From the commented out code in ```_hrtf.py``` it looks like the HRTFs should be in an array with ```shape=(2, n_angles, n_time_points)``` and there should also be a list of angles that are of type ```float``` (seems like it will bomb if the type were accidentally ```int``` given the way it's written to a file). It also appears that the RMS of the central one when convolved with a bunch of white noise should be normalized 1. The sampling rate is hard coded to 44100 in ```get_hrtf```, so I will resample mine to be that.

@drammock and @Eric89GXL can you confirm this spec for me?

Now that we have HDF5 support, should we change the file format to that, with variables for the data, the angles, and the sampling rate? I can do whatever standard we decide on, we should just make sure it's fully documented, rather than inferred from code. I'll add that documentation once confirmed.

**Comment by Eric89GXL** [comment]
Fixed by #180
