### ISSUE TITLE
`git bisect` docs

### ISSUE THREAD

**Issue by Eric89GXL** [LABSN/expyfun#230]
We should add a section in `git_flow.rst` on `git bisect` on how to find errors, see:

http://webchick.net/node/99

@drammock @lkishline @deanp3 do one of you have time for it? Basically we could just adapt that step-by-step description from the website (and give credit). I think it should go in the developers section of our doc.

**Comment by lkishline** [comment]
Sure. Thursday and Friday I would have time to do this if no one else can.

On Monday, April 27, 2015, Eric Larson <notifications@github.com> wrote:

> We should add a section in git_flow.rst on git bisect on how to find
> errors, see:
>
> http://webchick.net/node/99
>
> @drammock <https://github.com/drammock> @lkishline
> <https://github.com/lkishline> @deanp3 <https://github.com/deanp3> do one
> of you have time for it? Basically we could just adapt that step-by-step
> description from the website (and give credit). I think it should go in the
> developers section of our doc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LABSN/expyfun/issues/230>.
>


-- 
Lindsey Kishline
Graduate Student
Laboratory for Auditory Brain Sciences & Neuroengineering
ILABS
Department of Speech and Hearing Sciences
Tel: 206-616-0102

**Comment by Eric89GXL** [comment]
Assigned to you, thanks @lkishline

**Comment by lkishline** [comment]
Just found an email about this. Completely forgot about it last Thursday, apologies. I have blocked off a 2 hour chunk of time for it tomorrow morning.

**Comment by lkishline** [comment]
Welp. I've done something...what I did, I am not completely sure.
I am not sure if I did the pull request thing correctly. Was just trying to show you a working draft to get some comments on what I need to add or change...

**Comment by Eric89GXL** [comment]
Opening a PR is the best way to get feedback. It doesn't look like you opened one, though. It would show up here:

https://github.com/LABSN/expyfun/pulls

You could try following this to get it working:

https://github.com/LABSN/expyfun/blob/master/git_flow.rst#developers

Save your modified version of your file somewhere else just to safe in case you overwrite it.

**Comment by lkishline** [comment]
Yes, I did follow the instructions on the git_flow page. I think the issue is that it used the 'fix_branch' from the one we did the 'stupid_pyglet' thing on. I'll try and redo it.

**Comment by Eric89GXL** [comment]
Yeah usually you want to create a new branch based off `upstream/master` for each new PR

**Comment by Eric89GXL** [comment]
...feel free to update `git_flow.rst` to make that clearer once it makes sense to you

**Comment by lkishline** [comment]
Well, I gotta run to MEG now but I tried it again and accidently sent it to my fork...I will get this right eventually....
