### ISSUE TITLE
ENH: more stringent version checking

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#253]
Propose adding a new, mandatory argument to `ExperimentController` called `expyfun_version` (or maybe just `version`?), that accepts a string (7-character GitHub commit hash) or `None`.  This argument would have no default, so users would be **required** to provide it, thus making the change non-backwards-compatible.  On init, the existing `expyfun.assert_version()` would be used to check the version string; specifying `None` would simply not run the check.  The ability to use `assert_version` *outside* of an `ExperimentController` instance would remain, so that it could be used in scripts that only do stimulus generation, plotting, etc.

@rkmaddox and I just discussed this, want to run it by you @Eric89GXL before we start hacking.

**Comment by Eric89GXL** [comment]
That's reasonable, but in order not to break argument order I'd just put it at the end with `version=''` by default. If `version=None` then don't check.

**Comment by Eric89GXL** [comment]
(it's another way of requiring people to set it explicitly while breaking backward compat less)

**Comment by rkmaddox** [comment]
That makes sense. Or even make the default string `'must_set'` or something.
