### ISSUE TITLE
download_version not working in current master on Windows

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#256]
On MARLO, the following:

```python
from expyfun import download_version
download_version()

Traceback (most recent call last):
  File "C:\Experiments\drmccloy\prf\prf.py", line 12, in <module>
    download_version()
  File "c:\users\labsner\python\expyfun\expyfun\_git.py", line 56, in download_version
    _check_git()
  File "c:\users\labsner\python\expyfun\expyfun\_git.py", line 24, in _check_git
    raise RuntimeError('git not found: {0}'.format(str(exp)))
RuntimeError: git not found: [Error 2] The system cannot find the file specified
```

in git bash:
```sh
$ which git
/bin/git

$ pip show gitpython
---
Name: GitPython
Version: 0.1.7
Location: c:\winpython-32bit-2.7.6.4\python-2.7.6\lib\site-packages
Requires:
```

What am I doing wrong here?  download_version has worked before on MARLO, hasn't it?

**Comment by Eric89GXL** [comment]
I thought so, but maybe I just always copied a version over there. I can try it on my Windows laptop to see if I can reproduce it.

**Comment by drammock** [comment]
problem here appears to be that `C:\Program Files (x86)\Git\bin` is not on the system path: 

```python
>>> import os
>>> path = os.environ.get("PATH", "").split(os.pathsep)
>>> np.array(path)[np.where(['x86' in x for x in path])]
array(['C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common',
       'C:\\Program Files (x86)\\MATLAB\\R2013b\\bin',
       'C:\\Program Files (x86)\\SR Research\\Eyelink\\LIBS',
       'C:\\Program Files (x86)\\SR Research\\Eyelink\\EDF_Access_API\\lib\\win32',
       'C:\\Program Files (x86)\\SR Research\\Eyelink\\EDF_Access_API\\Example'], 
      dtype='|S68')
```

The reason why GitBash still works despite this is that the GitBash executable is in `C:\Program Files (x86)\Git`, so `bin` is `.\bin` in that case.

**Comment by drammock** [comment]
Should I add `C:\Program Files (x86)\Git\bin` to the MARLO system path and forget about it?  Or should we try to do some clever things within the expyfun code to find it even if it's not on the path?

**Comment by drammock** [comment]
I can confirm that adding `C:\Program Files (x86)\Git\bin` to the MARLO system path worked (after reboot).

**Comment by Eric89GXL** [comment]
I guess that's good enough. Closing, feel free to reopen if you think we could do something more systematic (I don't think it would be easy). It *might* be possible that using `shell=True` in the underlying `subprocess` call would have worked, but it's not recommended to do that. So I prefer this solution.

**Comment by drammock** [comment]
Maybe deserves mention in the docs somewhere, but I agree that trying to
hack this fix into _git.py is not worth the effort. Leaving closed.
