### ISSUE TITLE
screen_prompt not working in current master

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#257]
on MARLO

```python
from expyfun import ExperimentController
with ExperimentController(**kwargs) as ec:
    ec.wait_secs(1)
    # ec.flip()
    ec.screen_prompt('foo', wrap=False, max_wait=3)
    ec.screen_prompt('bar', wrap=False, max_wait=3)
```

result is that "foo" appears on screen for about the duration of 1 frame, then black screen for ~3 seconds, then "bar" for 3 seconds.  If the `ec.flip()` line is *not* commented out, `screen_prompt` behaves normally.  I think this issue came to light once before, but I don't remember the resolution (if there was one)...

**Comment by Eric89GXL** [comment]
Stupid workaround, but we should just call `flip()` at the end of `__init__`. Can you see if that fixes it?

**Comment by drammock** [comment]
yes, that fixes it.  I'm remembering now that last time this came up, someone was resistant to building in the `flip` into `init` but I don't recall why.  Should I roll this into my next PR then?

**Comment by Eric89GXL** [comment]
Yeah sure
