### ISSUE TITLE
ENH, FIX: Per-computer level calibration

### ISSUE THREAD

**Issue by rkmaddox** [LABSN/expyfun#263]
Currently the unity-RMS output level (in dB) is set based on the TDT in use (RP2 vs. RZ6). This implies that 1) all TDTs of the same model are consistent in their output levels (fair) 2) we are always using the same headphones and they are all perfectly calibrated to each other (less fair).

This came up because we need to change the calibration for the booth in 226, but we do not want to change it for 204. The solution seems to be allowing a calibration parameter in the `expyfun.json` file, but this is a little tricky, since that file doesn't change when a new version is checked out, and in particular, old versions of `expyfun` wouldn't respect it. (but maybe that doesn't matter?)

So, is the solution to add an `RMS_UNITY` system config parameter? And if so, what should its default setting be?

**Comment by Eric89GXL** [comment]
> that file doesn't change when a new version is checked out, and in particular, old versions of expyfun wouldn't respect it

As long as we don't change any parameters that are currently used in `master`, and *new* parameters we add shouldn't affect behavior of old scripts. So really we can name the parameter whatever we think makes sense. I don't think `RMS_UNITY` is quite verbose enough to make it clear what it means.

**Comment by rkmaddox** [comment]
OK, that's what I thought regarding adding new parameters. How about `DECIBELS_AT_UNITY_RMS`?

**Comment by Eric89GXL** [comment]
`DB_AT_1K_UNIT_RMS`?

**Comment by Eric89GXL** [comment]
`1KHZ`

**Comment by rkmaddox** [comment]
Decided to go entirely liter: `DB_OF_SINE_AT_1KHZ_1RMS`

**Comment by Eric89GXL** [comment]
Fine by me

**Comment by Eric89GXL** [comment]
You up for making a PR?

**Comment by rkmaddox** [comment]
Yep, already on it. Adding some other fixes as well.

**Comment by rkmaddox** [comment]
I guess I should leave a default out of the file, since it would supersede the device specific setting? I would put it in there and comment it out, by I don't think JSON files have comments, do they?

**Comment by Eric89GXL** [comment]
Which file are you leaving it out of? I'm not quite sure what you mean.

**Comment by rkmaddox** [comment]
The initial `expyfun.json` file. The way I'm coding it, a constant in there will supersede the hard-coded (in `expyfun`) device setting.

**Comment by rkmaddox** [comment]
(I can't think of any other way to code it, that is)

**Comment by Eric89GXL** [comment]
You mean when the file is written for the first time on a given machine? You could just not write out the constant at all. Then the admin can be expected to manually do `set_config(...)` or edit the file by hand to put the correct value in.

**Comment by rkmaddox** [comment]
Ohhh so that file doesn't get created on install? That would explain why I couldn't find a default file in the repo.

**Comment by Eric89GXL** [comment]
I don't think it does. Only once `set_config(...)` is called.

Also if it's not too difficult it would be good to do the same things for `key=None` in `get_config` and `set_config` that mne-python does, it would facilitate this process later.

https://github.com/mne-tools/mne-python/blob/master/mne/utils.py#L1036
https://github.com/mne-tools/mne-python/blob/master/mne/utils.py#L1186

It would also be good to document somewhere that no file is written by default, so if you want to deviate from the basic settings, you need to use `set_config(...)`. Once your PR is merged I can update the `expyfun` documentation.

**Comment by rkmaddox** [comment]
Sure, I can do that. So for `set_config`, make `None` give the list of options, and then add `get_config_path`?

**Comment by Eric89GXL** [comment]
Don't worry about the `get_config_path`, that was a bit of an overkill for corner cases in mne-python we haven't hit here. Basically `set_config(None)` should return a tuple of all the settable keys, and `get_config(None)` should return all the key, value pairs that are set in the current `.json` file.

**Comment by rkmaddox** [comment]
Ah, gotcha.

**Comment by drammock** [comment]
This raises an issue with our new computer setup scripts too... I'll try to
remember to add a little set_config script to that repo so that initial
expyfun setup is easier and better documented there as well.

**Comment by rkmaddox** [comment]
See #264 for fix.

**Comment by Eric89GXL** [comment]
Fixed by #264 but @rkmaddox hasn't absorbed the zen of "Closes #XXX" yet

**Comment by rkmaddox** [comment]
My B. I'll submit an issue that I am failing to close issues.

--
Ross Maddox, Ph.D.
Postdoctoral Fellow
Institute for Learning & Brain Sciences
University of Washington
phone: 206-685-4662
http://faculty.washington.edu/rkmaddox/

**Comment by Eric89GXL** [comment]
Just don't forget to put "Closes #XXX." by itself on a line so it auto-closes itself
