### ISSUE TITLE
adding video support

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#267]
before I get too deep into coding this up, I want to solicit input about where to add the code and how to organize. My initial thinking is:

- a `Movie` class in [_visual.py](https://github.com/LABSN/expyfun/blob/master/expyfun/visual/_visual.py) with methods play, stop, get_volume, set_volume
- various public and private methods/properties added to `ExperimentController`, such as:
    - `ec.player` (accessing `pyglet.media.Player` instance, analogous to `ec.window`)
    - `ec.load_movie()`
    - etc

Some questions / possible API changes:
- things like `ec.play()`, `ec.playing` etc: should they be changed to `ec.play_audio()` and `ec.audio_playing`, for parallelism with the to-be-added `ec.play_video` and `ec.video_playing`?
- what to do about the audio streams associated with loaded video files?  My current use case doesn't need them (I explicitly removed them when encoding, in fact) so for now could be ignored as YAGNI?
- dealing with video frame rate vs `ec.flip()`.  This sounds like a nightmare.  A possible easy solution for now would be to disable drawing and flipping while `ec.video_playing` is True.

Thoughts?

**Comment by Eric89GXL** [comment]
> things like ec.play(), ec.playing etc: should they be changed to ec.play_audio() and ec.audio_playing, for parallelism with the to-be-added ec.play_video and ec.video_playing?

It makes things a little bit more verbose. Maybe nesting it one like `ec.video.play()` or something would work?

> what to do about the audio streams associated with loaded video files? My current use case doesn't need them (I explicitly removed them when encoding, in fact) so for now could be ignored as YAGNI?

Yes I would for now just say they won't be played (and make sure Pyglet doesn't actually play them).

> dealing with video frame rate vs ec.flip(). This sounds like a nightmare. A possible easy solution for now would be to disable drawing and flipping while ec.video_playing is True.

For a first pass I'd just say in the docstring that it's not supported. But if you want to disable flips, preferably with an error message, during playback that's fine, too. I have a feeling disabling drawing would be more annoying, but you could try that too.
