### ISSUE TITLE
can't easily remove on_every_flip functions

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#269]
I want to add an element to `ec.on_every_flip_functions`, then later remove it.  I don't think there's a good way to do that, since it's a `@property`.  In theory I can access private list `ec._on_every_flip`, search through it, and `pop` the appropriate element (which for the current use case is fine because I'm doing this within `_visual.py`).  That *would* work well if I called `functools.partial` *before* passing into `ec.call_on_every_flip` so that I could compare the objects directly, but it's less straightforward because `ec.call_on_every_flip` calls `functools.partial` internally, making it a bit ugly to keep track of what gets passed in, so as to later compare `ec._on_every_flip` list elements to it. Example:

```python
# here self._draw is <type: functools.partial> already
for idx, func in enumerate(self._ec._on_every_flip):
    if hasattr(func, 'func'):
        if func.func is self._draw:
            self._ec._on_every_flip.pop(idx)
```

possible changes/solutions:

1. make `ec.on_every_flip_functions` read/write, possibly by adding a new `remove_on_every_flip` method.
1. alter `ec.call_on_every_flip` to return the partialized function, so you can compare against it with `is` later when iterating through `ec._on_every_flip`.
1. alter `ec.call_on_every_flip` to generate a dict instead of list, and have it return a key, so it can be deleted easily later.
1. alter `ec.call_on_every_flip` to check whether its incoming function is already a partial, and if so, don't call partial on it again.
1. alter `ec.call_on_every_flip` to not call partial at all, and leave it up to the user to call it before passing in the function.

Thoughts?

**Comment by Eric89GXL** [comment]
Let's get rid of the internal `partial` call, users can learn how to use it instead of us doing it for them.

Then you can just do `ec.on_every_flip_functions.pop(ec.on_every_flip_functions.index(my_fun))` right?

**Comment by drammock** [comment]
I'm in favor of that option too, although isn't there an additional step of making `ec.on_every_flip_functions` read/write, in order to allow `.pop()` to work?  In which case do we want to do that, or instead add a method like `ec.remove_from_every_flip`?

**Comment by Eric89GXL** [comment]
If it returns the list (without copying), lists are mutable so `.pop` will work

**Comment by drammock** [comment]
FYI I have a local branch implementing this change already, but am waiting
until after the video PR is finished to push / PR.  it will necessitate a
small change in the video code, so I'm erring on the side of doing my
rebase locally before the second PR gets opened.
