### ISSUE TITLE
Error on download_version

### ISSUE THREAD

**Issue by rkmaddox** [LABSN/expyfun#271]
We are trying to download a legacy version of `expyfun` but getting the following error:

``` python
>>> expyfun.download_version('090948e')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\labuser\builds\expyfun\expyfun\_git.py", line 94, in download_version
    assert git_version()[0].lower() == version[:7].lower()
AssertionError
```

When I do `pdb` I get that `git_version()` is `'Unknown'`. Any ideas?

**Comment by rkmaddox** [comment]
@Eric89GXL please drop what you are doing and respond right away.

**Comment by Eric89GXL** [comment]
Does the machine have git installed?

**Comment by drammock** [comment]
yes it does. looks like the problem involves checking out a sufficiently old version of expyfun such that the `git_version()` function in `setup.py` (loaded from the temp directory just created) still returns a single value (`VERSION`) rather than a tuple `(VERSION, FORK)`, and then passes it to a newer version of the `download_version` function (which is expecting a tuple, not a string).

**Comment by drammock** [comment]
importing `git_version` (and `setup_package`) from *current expyfun* instead of *downloaded version of expyfun* might fix it, except for the fact that `git_version` (being located in `setup.py`) is not a proper part of the package.

**Comment by Eric89GXL** [comment]
It's annoying, but the easiest solution is probably just to do the `git` commands (and perhaps editing of `__init__.py` or a version file) yourself to get the correct version.

How old is the commit number you're going for? Did we have `download_version` back then?

**Comment by Eric89GXL** [comment]
Looks like it did, from back in August '14:

https://github.com/LABSN/expyfun/blob/090948e35f20322a325b42f8b9098bd0fefaed71/expyfun/__init__.py

@rkmaddox do you plan to do this often? If so we should fix. If not, we should probably just do it manually for this or the couple of cases we need to.

**Comment by rkmaddox** [comment]
Well, it's an older experiment that has an assert_version call in it. Seems
like download_version should work. I am quite disinclined to make people do
the git themselves, as that's a pretty big barrier for most (myself
included).

--
Ross Maddox, Ph.D.
Postdoctoral Fellow
Institute for Learning & Brain Sciences
University of Washington
phone: 206-685-4662
http://faculty.washington.edu/rkmaddox/

**Comment by rkmaddox** [comment]
Seems like the solution is to make git_version a part of expyfun itself
(and not part of setup.py), and have setup.py call it from there. Is there
a problem with doing that?

--
Ross Maddox, Ph.D.
Postdoctoral Fellow
Institute for Learning & Brain Sciences
University of Washington
phone: 206-685-4662
http://faculty.washington.edu/rkmaddox/

**Comment by Eric89GXL** [comment]
Ahh, so you're thinking e.g. for publications we need to make it work properly?

IIRC there is a bit of a chicken-and-egg problem with getting `download_version` to work properly (even when opening PRs it's tough to get right). It's likely that old version never quite worked properly. Maybe migrating to using `expyfun.*` would work. Have time to give it a try? ha ha ha ha...

**Comment by mfreilly** [comment]
TDT front panel Digital I/O LEDs 4 5 6 7 light when buttons pressed.
TDT input is A5 A6 A7 A8.
keypress_demo.py does not respond to press.
expyfun commit version: can't tell, is Git installed on Nintok? I don't see it.
But looks like Dan installed expyfun 11/15/16.

**Comment by Eric89GXL** [comment]
Great, at least the hardware issue seems solved. LEDs on the TDT mean that it should be possible to get the data into the circuit. Now we just need to figure out the software end...

**Comment by Eric89GXL** [comment]
@rkmaddox can we close this? Maybe YAGNI?

**Comment by drammock** [comment]
@Eric89GXL this bug might actually go away once we've done away with `__FORK__`

**Comment by drammock** [comment]
Indeed, in my local testing today I used the same commit that was giving you grief, and it works again now that download_version no longer returns a tuple of (hash, fork) and instead only returns the hash string.
