### ISSUE TITLE
audio buffer load time vs video frame rate

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#277]
I'm hitting the issue that the time it takes to load a syllable-length audio stim (range from 150-750ms) into the TDT buffer (takes ~30ms) is longer than the video frame period (~23ms), so the video is dropping frames almost every single time a new stimulus is loaded.  I've tried everything I can think of that doesn't require altering the circuit:

- setting `ec.load_buffer` as a partialized `call_on_next_flip` function, to give it the maximum amount of time to complete before next flip is due
- splitting `ec.load_buffer` into separate `ec._ac.rpcox.WriteTagV` calls, so that I can do an `ec.flip()` in between loading the left and right channels into the buffer

any other ideas @Eric89GXL @rkmaddox ?

**Comment by Eric89GXL** [comment]
You need the C routines I haven't written yet :( Then it will create zero lag for your experiment, assuming you don't need to continuously *poll* the keypresses (responses will be recorded with high fidelity, but requesting the values could be slow).

What's your timeline for the experiment?

**Comment by drammock** [comment]
Timeline is we were supposed to start in February :(

**Comment by Eric89GXL** [comment]
2017?

**Comment by drammock** [comment]
for now, have found a workable solution using `subprocess.Popen` to run the video in a separate thread using VLC (which has handy command-line args to make it fullscreen and auto-close when finished).  Closing.
