### ISSUE TITLE
ENH: make ec._playing more accurate via polling

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#278]
motivated by changes made in #266, the hard requirement to call `ec.stop()` in between subsequent calls to `ec.play()` (and the corresponding `ec._playing` property that kept track of this) has been called into question.  However, as @Eric89GXL notes:

> we probably don't want people doing `.load_buffer` before the stimulus is done playing, and we probably don't want them doing that before `.trial_ok()` is called -- and we need `ec._playing` for that.

**Comment by Eric89GXL** [comment]
I think it's safest to leave `._playing` in place, and just make it actually poll. @drammock you okay with that?

**Comment by Eric89GXL** [comment]
Removing requirement for `.stop` while leaving `._playing` in place is done in #266 now

**Comment by drammock** [comment]
eliminating the requirement for `stop()` is enough to make me happy.  I'm neutral on the question of polling; if its impact is negligible I don't object. Renaming issue to reflect that.
