### ISSUE TITLE
ENH: allow button-box input to TDT in RZ6 circuit

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#282]
Circuit changes were implemented in #266 (lots of discussion on that thread), but hardware issues with the buttons and switchbox made testing difficult at the time.  Needs testing / debugging / possibly more circuit changes.  cc @rkmaddox @mfreilly

**Comment by drammock** [comment]
At present, the switchbox passes presses to expyfun via USB, by presenting itself as a keyboard.
This proposed enhancement is possible as far as expyfun is concerned, by passing `response_device='tdt'` when `ExperimentController` is instantiated (or by changing the machine config file), and I'm assuming that the updated RZ6 circuit is configured to accept button presses (right @Eric89GXL?)  The bottleneck seemed to be getting the switchbox to pass the signals to the TDT reliably.  @mfreilly did you ever re-test this after the switchbox got upgraded?

**Comment by Eric89GXL** [comment]
I *think* that was the issue, yes.

**Comment by mfreilly** [comment]
I have not tested it since the fix, I'll look at this today. I assume the output of the Elekta trigger box goes to TDT digital inputs. If so which ones?

**Comment by Eric89GXL** [comment]
It probably needs to be connected to the first four ports of block A. If that doesn't work, try B. If that doesn't work, try the four ports of block C that are not connected as outputs to the TDT.

The output trigger lines are connected to the first four ports of block C, right?

**Comment by mfreilly** [comment]
A is the output of the TDT to the Elekta trigger inputs. I'll try B and C. Nothing is connected to C now.

**Comment by mfreilly** [comment]
Tried response_device='tdt' and patched the Trigger box outputs to TDT A, B, and C.
Ran keypress_demo.py, got 'no keys pressed'

**Comment by drammock** [comment]
@mfreilly in the keypress demo script, did you edit it to specify `response_device='tdt'` when `ExperimentController` is instantiated?  If not, expyfun will default to `'keyboard`' based on NINTOK's config file, and wouldn't register the responses even if they were making it through to the TDT.

**Comment by drammock** [comment]
@mfreilly never mind, I misread your comment.

**Comment by Eric89GXL** [comment]
@drammock didn't we have it in a state where *some but not all* of the triggers came through? I wonder if we broke something.

@mfreilly did you make sure that the version of `expyfun` being imported/used is the one from latest `master`?

**Comment by drammock** [comment]
prior to the switchbox upgrade, we did get it working such that button presses would register on the TDT sometimes, but not always.  It wasn't "some buttons and not others"... it seemed to depend on how long/hard you pressed the button.  For quick presses you would see LED flashes on the switchbox, but not on the TDT input indicator LEDs.

**Comment by Eric89GXL** [comment]
Hmm... I suspect that the TDT indicator LEDs should come on almost regardless of what port they're plugged into (at least as long as they're in an input port). @mfreilly did you see any lights on the TDT come on when you pressed buttons? I assume you did see lights on the Elekta box?

**Comment by mfreilly** [comment]
Will check things this morning

**Comment by Eric89GXL** [comment]
From the other issue:

> TDT front panel Digital I/O LEDs 4 5 6 7 light when buttons pressed.
> TDT input is A5 A6 A7 A8.
> keypress_demo.py does not respond to press.
> expyfun commit version: can't tell, is Git installed on Nintok? I don't see it.
> But looks like Dan installed expyfun 11/15/16.

Within the circuit, port C0-3 are the only ones marked as "output", all other ports (all of A, B, and C4-7) are all marked as "input". @mfreilly I wonder if there is some mis-labeling or swapped cables.

Do any LED lights come on when you connect it to B ports?

**Comment by Eric89GXL** [comment]
In the circuit there is even a comment "This will access only 4 bits of Port-C of the Digital IO." for the TTL line outputs. It seems like the correct configuration would be to have the first 4 ports of C outgoing to the Neuromag...

I wonder if the labels A/C are swapped. @mfreilly can you try with the button box plugged into the first four ports of B, and then of C? Do any lights come on? Any different behavior of the circuit?

**Comment by mfreilly** [comment]
Sorry, responded on wrong issue.
Buttons in B1 -B8, C1 - C8. No response

**Comment by Eric89GXL** [comment]
To confirm what you mean by no response -- the script did not respond *and* there were no LEDs that came on the TDT, right?

I think this will require local debugging of the circuit unfortunately.

@mfreilly on the experimental computer, can you:

1. make a new folder, say "testing"
2. Copy the latest version of `expyfun` `master` in it, probably easiest to do `expyfun.download_version()` on some computer and copy the result
3. Put `plot_keypress_demo.py` in the testing folder
4. Run `plot_keypress_demo.py`, quit out of it, and do `print(expyfun)` within Python to ensure that it is importing it from the local directory
5. Open the `testing\expyfun\data\expCircuitF32_RZ6.rcx` file (it should automatically open in RPvdsEx)
6. Go to the "waitForButtonPress" tab at the bottom
7. Try doing menu `Implement->Build, Load and Run`. This gets the circuit loaded and running on the TDT.
8. See if the rightmost (middle center) tag in the circuit does anything when pressing buttons
9. Stop the circuit (Implement->Halt circuit), change the bitmask (leftmost component) from 255 to 65280, and repeat steps 7-8
10. Stop the circuit, change the bitmask to 16711680, repeat steps 7-8

Hopefully one of these steps produces a non-zero output on the monitor. If it doesn't, I can make a simpler circuit for testing.

**Comment by mfreilly** [comment]
Correct: the script did not respond and there were no LEDs that came on the TDT
I'll do the setup

**Comment by mfreilly** [comment]
keypad connected to B1 B2 B3 B4
Installed expyfun in /keypress_test
print(expyfun) result = <module 'expyfun' from 'expyfun\_init_.py'>
On  keypresses there is no visible change in the circuit.

**Comment by Eric89GXL** [comment]
The print result was blank? 

That was steps 1 through 4 essentially, right?

**Comment by Eric89GXL** [comment]
Although the last line makes it sound like you also did through step8

**Comment by mfreilly** [comment]
The print result is blank.

**Comment by Eric89GXL** [comment]
You are doing it within the python interpreter? I'm not sure how it's
possible it is blank with no error or anything. Does print(1+1) give
anything?

**Comment by mfreilly** [comment]
print(1+1) result = 2
Also on CTRL-C it stops with KeyboardInterrupt but there is no command line open in the console.

**Comment by Eric89GXL** [comment]
Try doing

import expyfun
print(expyfun)

Maybe it wasn't imported by the script you are running and Spyder just hid
the error

**Comment by mfreilly** [comment]
import expyfun
print(expyfun)
<module 'expyfun' from 'expyfun\__init__.pyc'>

Also:
import numpy
print(numpy)
<module 'numpy' from 'C:\WinPython-32bit-2.7.6.4\python-2.7.6\lib\site-packages\numpy\__init__.pyc'>

assert in keypress_tesst.py
assert_version('aaaaaaa')
AssertionError: Requested version aaaaaaa does not match current version 25b25ea
This is the commit in the test folder

**Comment by Eric89GXL** [comment]
Okay, so we're at least on the latest `master`. Have you tried steps 5+ yet?

**Comment by mfreilly** [comment]
Did steps 5 - 10. No changes seen in waitForButtonPress

**Comment by Eric89GXL** [comment]
Hmmm.... how about this. First modify the components in waitForButtonPress -- instead of reading out on the rightmost part of the For each mask value (255, 65280, 16711680):

1. Add a Watch (Components->Common->Watch)
2. Hook up the input component (leftmost component) to the ParWatch by by double-clicking the output triangle of the 10110100-triangular component, and then clicking the input triangle of the ParWatch
3. Stop the circuit (if it's running)
4. Change the mask value
5. Load and run the circurt
6. Press buttons, see if the ParWatch changes
7. Try steps 3-6 for all set-of-four input connections (A5-A8, B1-B4, B5-B8, C1-C4, C5-C8)

It seems like one of these must work...

Sorry this is such a pain

**Comment by Eric89GXL** [comment]
Actually to make it really easy you could just add three inputs (Componetns->Input/Output; WordIn) with the three different mask values, each hooked up to their own ParWatch. Then once that circuit is running, you only need to switch the cables to each location once!

**Comment by mfreilly** [comment]
Progress, the new watch changes with inputs on C1 thru C8.
Not a pain, a good intro to circuits

**Comment by Eric89GXL** [comment]
Excellent! @mfreilly let's iterate on Gitter so we don't slam GitHub notifications

https://gitter.im/LABSN/expyfun

**Comment by Eric89GXL** [comment]
It looks like this works as long as all 8 buttons are connected to input B. The problem was that B5-8 being disconnected appeared as HIGH to the TDT, so it looked like all those buttons were permanently pressed (value 240 was constant).
