### ISSUE TITLE
Documentation title says "MNE"

### ISSUE THREAD

**Issue by rkmaddox** [LABSN/expyfun#289]
If you go to the [documentation](http://labsn.github.io/expyfun/index.html), it says "MNE 2.0.0.dev0" instead of expyfun.

**Comment by drammock** [comment]
hmm, if I follow that link it doesn't say "mne" anywhere...  @Eric89GXL did you secretly fix this already?

**Comment by drammock** [comment]
oh... I see it, in the window title.

**Comment by Eric89GXL** [comment]
All better, CircleCI pushed new docs after merge of #290
