### ISSUE TITLE
Controller version type error on older versions

### ISSUE THREAD

**Issue by kambysese** [LABSN/expyfun#309]
@drammock kwarg 'version' to `ExperimentController` returns with "...unexpected keyword argument" with older versions e.g. 'c8141cc' and '8511a4d'.

**Comment by Eric89GXL** [comment]
Yes it was added at some point and does not exist on old versions. Why is
this a problem?

**Comment by drammock** [comment]
@kambysese the version checking was added [2 years ago](https://github.com/LABSN/expyfun/commit/393e9ae92f63f1afd0e8c61d3187468fadaef3dc).  Why do you want/need versions of expyfun older than that?

**Comment by kambysese** [comment]
@drammock no particular reason. Those are just the versions I froze at.
