### ISSUE TITLE
FIX: Eyelink origin discrepancy

### ISSUE THREAD

**Issue by maddycapp27** [LABSN/expyfun#317]
After setting up the eyelink I noticed that there was a discrepancy between coordinate systems.

`el.get_eye_position()` returns location in pixels with the center of the screen being `[0, 0]`. The eyelink itself claims to output a location where the top left is `[0, 0]` (but it seems more like it's using the bottom left). `ec._convert_units()`, however, assumes that the pixel locations use the bottom left of the screen as `[0, 0]`.

Since `el.wait_for_fix()` uses both `el.get_eye_position()` and `ec._convert_units()`, the coordinates never match up.

**Comment by Eric89GXL** [comment]
This is strange. Does this example work properly on your computer with the Eyelink?

https://github.com/LABSN/expyfun/blob/master/examples/experiments/eyetracking_experiment_.py

**Comment by maddycapp27** [comment]
@Eric89GXL @drammock @rkmaddox 

I wonder if this is happening because of using a different version of the eyelink.

Also I'm not familiar with how issues work, do I have to be assigned (by someone with permissions to do so) before I can do stuff?

**Comment by maddycapp27** [comment]
@Eric89GXL I was using that example and it only started working when I added in [960, 540] to the eye position to get everything to agree

**Comment by Eric89GXL** [comment]
> Also I'm not familiar with how issues work, do I have to be assigned (by someone with permissions to do so) before I can do stuff?

No you can open PRs whenever you want. The assigning and such is just helpful if we want to use it (but usually don't need to for a repo this size).

> I wonder if this is happening because of using a different version of the eyelink.

Yes it's possible. Which version of pylink (or whatever they call it) are you using, and which Eyelink? I thought I tested that example on our system, but maybe I didn't.

In any case, it's worth making a PR to fix the calculation for your system. Then we can try it back in Seattle. It might take a couple of weeks for us to get to it, though.

**Comment by drammock** [comment]
This is indeed surprising. Since I'm gone for 2 weeks, maybe we can get @lkishline or @shbaum to test now just to confirm it works as-is?

**Comment by drammock** [comment]
@Eric89GXL @maddycapp27 what ever happened with this?

**Comment by Eric89GXL** [comment]
Fixed in https://github.com/LABSN/expyfun/pull/318

**Comment by drammock** [comment]
huh.  somehow I missed that whole thread.  Maybe I accidentally muted it.

**Comment by Eric89GXL** [comment]
Did you get notified about #320? If not, maybe you aren't being notified about PRs anymore

**Comment by drammock** [comment]
yes I did.  I think I must have muted or archived the #318 thread through my inbox without ever reading it (i.e., user error, not a change in GitHub's behavior toward me).
