### ISSUE TITLE
BUG: TrackerDealer logging insufficient

### ISSUE THREAD

**Issue by larsoner** [LABSN/expyfun#326]
The TrackerDealer gets initialized with a `rand` argument, but this isn't anywhere in the `dealer_%i_init` line, so it can't actually be reconstructed. @rkmaddox this is a bug, right?

**Comment by rkmaddox** [comment]
No, because of the way it works. Because of the randomness aspect, we opted to have `reconstruct_dealer` work by setting the private variables directly, rather than go through and rebuild it trial-by-trial like we did with `reconstruct_tracker`. Sound right, @maddycapp27?

**Comment by larsoner** [comment]
Ahh okay, makes sense.
