### ISSUE TITLE
FIX: Is it possible to set the sampling rate?

### ISSUE THREAD

**Issue by rkmaddox** [LABSN/expyfun#337]
I need to run an experiment at 48828 instead of the normal 24414 Hz. I am going to go up to the lab and poke around, but I wanted to ask in case anyone knew: can we set the sampling rate from `expyfun`, or does it need a new circuit for that?

**Comment by larsoner** [comment]
In principle you can control it in software, it gets set by the code initializing/running the circuit (not within the circuit itself). But in practice I'm not sure the extent to which we have hard-coded 24414. Hopefully not too much...?

**Comment by rkmaddox** [comment]
Can you point me to that line? I wasn't sure, because in the RPCoX docs I found a `GetSFreq` function but not a `SetSFreq`.

**Comment by larsoner** [comment]
I think we need to use `LoadCOFsf`

https://github.com/LABSN/tdtpy/blob/master/tdt/actxobjects/RPcoX.py#L176

**Comment by larsoner** [comment]
And from some light googling, I think you want to pass `3`:

https://github.com/psexton/MockObject/blob/master/example/RealtimeProcessor.m#L65

**Comment by rkmaddox** [comment]
Perfect, thank you. I will go give that a try.

**Comment by rkmaddox** [comment]
It was easy to modify the code, and there were actually surprisingly few places where `24414` came up.

However, it doesn't work. When I tell it to do 24k sampling rate it works. When I tell it to do 12k sampling rate it works. But when I tell it to do 48k sampling rate, it does 24. However, it thinks it's doing 48, since `ec.fs` is 48k when I ask. I am thinking it is a hardware problem.

**Comment by larsoner** [comment]
This might be the TDT "feature" that it silently falls back to a lower sampling rate if too many cycles are used at the requested sample rate

**Comment by rkmaddox** [comment]
Interesting. That's a good thought. I will poke around in the circuit a bit and see what I can find out.

**Comment by larsoner** [comment]
I'd load it up in the TDT circuit editor program, and try running it at 24414, look at the cycle usage (IIRC it's around 80%?) and then try running it at 48828, it will probably drop back down almost immediately

**Comment by larsoner** [comment]
... we might need to make a simplified circuit -- if we cut out the button press stuff, for example, it might really help. Do you need well-timed button presses for this experiment?

**Comment by rkmaddox** [comment]
I actually don't need button presses or noise for this experiment. I am going to try removing the noise generator first. Could be a simple flag in the `ec` init, since if noise is off at the beginning it is usually off for the whole experiment.

**Comment by rkmaddox** [comment]
You were right. I made a light version of the circuit that removed the noise generator, and did a couple other efficiency things. It works now. I will use my hacked version for my pilot today and then make a PR later today.

I also noticed that the time returned by `ec.start_stimulus` does not account for the `TDT_DELAY` parameter, which is 2 ms on my system. Not a huge deal, but seems like it should be adjusted to match as well as possible.

**Comment by larsoner** [comment]
> EDIT: later. not later today.

:)

> I also noticed that the time returned by ec.start_stimulus does not account for the TDT_DELAY parameter, which is 2 ms on my system. Not a huge deal, but seems like it should be adjusted to match as well as possible.

Agreed

**Comment by larsoner** [comment]
I'm going to close this as you can do it for sound cards, and YAGNI for TDT at this point (feel free to reopen if I'm wrong)

**Comment by rkmaddox** [comment]
Hooray sound cards!
