### ISSUE TITLE
Pyglet error

### ISSUE THREAD

**Issue by ktavabi** [LABSN/expyfun#344]
So it's been a while I've deployed expyfun. The following gist based on this [example](http://labsn.github.io/expyfun/auto_examples/experiments/drawing_methods.html#sphx-glr-auto-examples-experiments-drawing-methods-py) throws a `pyglet.window` `AttributeError` that for some reason doesn't happen when I run the example script.

PS. is there a more straightforward way of drawing a fixation cross?

```python
import numpy as np
from expyfun import ExperimentController
from expyfun.visual import Line
# set configuration
dur = 5.0
xy1 = np.array([[0, 0], [0, .05]])
xy2 = np.array([[0, 0], [0, -.05]])
xy3 = np.array([[-1, 0], [0, 0]])
xy4 = np.array([[0, 0], [1, 0]])
# instructions
instructions = ('blah blah blah')
with ExperimentController('testExp', participant='foo', session='001',
                          output_dir=None, version='dev') as ec:
    # show instructions
    ec.screen_prompt(instructions, live_keys=[9])
    ec.wait_one_press(max_wait=np.inf, live_keys=[9])
    line1 = Line(ec, xy1, units='deg', line_color='w', line_width=2.0)
    line2 = Line(ec, xy2, units='deg', line_color='w', line_width=2.0)
    line3 = Line(ec, xy3, units='deg', line_color='w', line_width=2.0)
    line4 = Line(ec, xy4, units='deg', line_color='w', line_width=2.0)
    # do the drawing, then flip
    for obj in [line1, line2, line3, line4]:
        obj.draw()
    ec.flip()
```
> Traceback (most recent call last):
>   File ".../Projects/genz/resting_state_pdm.py", line 34, in <module>
>     output_dir=None, version='dev') as ec:
>   File "<string>", line 2, in __init__
>   File ".../Projects/expyfun/expyfun/_utils.py", line 428, in verbose_dec
>     ret = function(*args, **kwargs)
>   File ".../Projects/expyfun/expyfun/_experiment_controller.py", line 237, in __init__
>     mon_size = pyglet.window.get_platform().get_default_display()
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/pyglet/__init__.py", line 384, in __getattr__
>     __import__(import_name)
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1776, in <module>
>     from pyglet.window.xlib import XlibWindow as Window
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 54, in <module>
>     from pyglet.canvas.xlib import XlibCanvas
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/pyglet/canvas/__init__.py", line 103, in <module>
>     from pyglet.canvas.xlib import XlibDisplay as Display
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/pyglet/canvas/xlib.py", line 16, in <module>
>     from pyglet.app.xlib import XlibSelectDevice
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/pyglet/app/__init__.py", line 154, in <module>
>     from pyglet.app.base import EventLoop
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/pyglet/app/base.py", line 4, in <module>
>     standard_library.install_aliases()
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/future/standard_library/__init__.py", line 483, in install_aliases
>     import test
>   File ".../Projects/genz/test.py", line 15, in <module>
>     output_dir=None, version='dev') as ec:
>   File "<string>", line 2, in __init__
>   File ".../Projects/expyfun/expyfun/_utils.py", line 428, in verbose_dec
>     ret = function(*args, **kwargs)
>   File ".../Projects/expyfun/expyfun/_experiment_controller.py", line 237, in __init__
>     mon_size = pyglet.window.get_platform().get_default_display()
>   File ".../miniconda3/envs/mne2/lib/python2.7/site-packages/pyglet/__init__.py", line 388, in __getattr__
>     return getattr(module, name)
> AttributeError: 'module' object has no attribute 'get_platform'

**Comment by drammock** [comment]
We don't have a cross, [we have concentric dots](https://github.com/LABSN/expyfun/blob/873ee3d8f1c3c981dadf350037aa48b9529d4c09/expyfun/visual/_visual.py#L803-L828).

**Comment by drammock** [comment]
When i run your script in a python 2 environment, I get no errors.  In py3 I get some pyglet depracation warnings, but no error.  What is `pyglet.version`?  (mine is `1.2.4`)

**Comment by drammock** [comment]
(by the way, if you want the window to stay open long enough for you to see your fixation cross, you should add another `wait` statement to the end of your script.  Otherwise the window will close instantly as soon as the flip happens)

**Comment by larsoner** [comment]
Did you install with `pip`? There is inexplicably some alpha version 1.4.0a1 on PyPi that I recall beincg broken. IIRC I've had to pin Pyglet to `1.2.4` or maybe `1.3.0` to avoid it, so if you installed via pip, try uninstalling and reinstalling `pyglet==1.2.4`.

**Comment by drammock** [comment]
yet another comment:  I think you're specifying the line coords wrong.  They should be `[[x1, x2], [y1, y2]]`.  So this:

```python
xy1 = np.array([[0, 0], [-1, 1]])
xy2 = np.array([[-1, 1], [0, 0]])
```

yields a fixation cross spanning 2 degrees visual angle in horiz. and vert. directions.

**Comment by ktavabi** [comment]
@larsoner pyglet-1.3.0 via `pip`. Removing and installing `pyglet==1.2.4` resolved the error.
@drammock thanks for the tips, worked like a charm! I was doing `[[x1, y1], [x2, y2]]`
