### ISSUE TITLE
BUG: CircleCI 1.0 is retiring

### ISSUE THREAD

**Issue by larsoner** [LABSN/expyfun#349]
... in August. So we need to migrate to 2.0. This *should* be pretty straightforward given that I've already done it for MNE-Python.

@drammock you can do it if you want to brush up on your CI skills, otherwise I'll do it.

**Comment by drammock** [comment]
wow, you got on that quick.  Thanks!  In a perfect world I would have liked to brush up on CI skills, but realistically wouldn't have gotten to it for a few weeks at least.
