### ISSUE TITLE
Issue with AVbin

### ISSUE THREAD

**Issue by cwenner2** [LABSN/expyfun#351]
I am trying to run some of the example code in expyfun, in particular simple_video.py, but each time I get the following error: 

"Traceback (most recent call last):

  File "<'ipython-input-5-ab29d452275f'>", line 1, in <module>
    runfile('C:/Users/bella/Python/expyfun/examples/stimuli/simple_video.py', wdir='C:/Users/bella/Python/expyfun')

  File "C:\Users\bella\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\bella\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/bella/Python/expyfun/examples/stimuli/simple_video.py", line 25, in <module>
    ec.load_video(movie_path)

  File "expyfun\_experiment_controller.py", line 787, in load_video
    r'Something is wrong; probably you tried to load a '

RuntimeError: Something is wrong; probably you tried to load a compressed video file but you do not have AVbin installed. Download and install it; if you are on Windows, you may also need to manually copy the AVbin .dll file(s) from C:\Windows\system32 to C:\Windows\SysWOW64."

I have confirmed that avbin.dll is in both folders. I have also attempted the following:
`import pyglet`
`pyglet.lib.load_library('avbin')`
but get the following error:

"Traceback (most recent call last):

  File "<'ipython-input-7-5cfd654a18aa'>", line 1, in <module>
    pyglet.lib.load_library('avbin')

  File "C:\Users\bella\Anaconda2\lib\site-packages\pyglet\lib.py", line 137, in load_library
    lib = ctypes.cdll.LoadLibrary(name)

  File "C:\Users\bella\Anaconda2\lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)

  File "C:\Users\bella\Anaconda2\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)

WindowsError: [Error 193] %1 is not a valid Win32 application"

I am using Windows 10 and Python 2.7.14 (32 bit). Any thoughts as to a solution?

**Comment by rkmaddox** [comment]
We have tried a bunch of things to no avail. The most important was changing to `pyglet==1.4.0a1`, which ditches `avbin` for `ffmpeg`.

Has anyone actually gotten this working in Windows? We might need to start from there. @cwenner2 and I aren't even getting the same errors...

**Comment by rkmaddox** [comment]
@drammock you have successfully used this on Windows for your experiments, right?

**Comment by larsoner** [comment]
Does `pytest expfun` work for you? If so, we have some testing deficiencies to sort out :(

**Comment by larsoner** [comment]
(The CIs test Linux, macOS, and Windows so this should really be caught by a test)

**Comment by larsoner** [comment]
I got the same error, then downloaded and executed:

https://github.com/downloads/AVbin/AVbin/AVbin10-win64.exe

And it worked.

**Comment by larsoner** [comment]
```
$ python --version
Python 3.6.3 :: Anaconda custom (64-bit)
```

**Comment by larsoner** [comment]
We do have tests for video but they are protected by `requires_avbin` decorator. Should we make `avbin` a hard dependency (for tests to pass at least)?

**Comment by drammock** [comment]
I have successfully used video playback for experiments on our Windows 7 system ("marlo").  We don't have any systems here running windows 10.

If we're going to add a hard dependency, it should be `ffmpeg` rather than `avbin`...  long story short: right around the time I developed the video playback code, the `ffmpeg` devs had a fight, `avbin` was born, and trumpeted itself as the actively maintained successor to `ffmpeg`.  Fast forward to today: the tables have turned, `avbin` is stagnant, and `ffmpeg` is still actively developed.

**Comment by larsoner** [comment]
@drammock can Pyglet < 1.4 use `ffmpeg`, though?

**Comment by drammock** [comment]
I just spent ~10 minutes trying to figure that out from the pyglet source code, and still can't really tell `<insert rant about bitbucket's U.I. here>`.  I may have to create a VM just to figure that out.

**Comment by drammock** [comment]
after a little more digging, it looks  like they switched to `ffmpeg` 2018 January 31.  Pyglet 1.3.2 was released in April, so in theory it should work with `ffmpeg`.  I'll try to make time to test that later today... I'll try to replicate @cwenner2's setup as closely as possible (py2.7, 32-bit), but I dunno if I can get my hands on Windows 10.

**Comment by larsoner** [comment]
I have my VM up and can check pretty quickly, at least for Py3k.

BTW numpy will stop new features for 2.7 at the end of this year. Time to start migrating!

**Comment by larsoner** [comment]
According to https://groups.google.com/forum/#!topic/pyglet-users/ah2I54BSrZg it's only 1.4.0a+. So let's do `avbin` for now.

**Comment by larsoner** [comment]
@rkmaddox did you try this variant:

https://stackoverflow.com/questions/10302873/python-pyglet-avbin-how-to-install-avbin#answer-47249531

**Comment by rkmaddox** [comment]
Just back from piloting an experiment. I will go back to `pyglet` version 1.3.2 and do your AVbin install. The strange thing is that `pyglet` is supposed to come with its own AVBin, and @cwenner2 had the dlls in the system folders. Will try that other link you just sent if it doesn't work.

**Comment by larsoner** [comment]
> @cwenner2 had the dlls in the system folders. Will try that other link you just sent if it doesn't work.

It depends on which DLL you put it which system folder. You can see which go where in #352:

https://github.com/LABSN/expyfun/pull/352/files#diff-a44785b136b7e4dafbc1d36fd2cf0980R7

**Comment by rkmaddox** [comment]
If I am reading that right---does it mean the 64 bit dll has to go in system32, and the 32 bit dll has to go in sysWOW64?

**Comment by larsoner** [comment]
https://www.howtogeek.com/326509/whats-the-difference-between-the-system32-and-syswow64-folders-in-windows/

**Comment by larsoner** [comment]
So yes :)

**Comment by larsoner** [comment]
(Assuming you are running a 32/64 bit versions of *Python* on a 64-bit version of *Windows*)

**Comment by rkmaddox** [comment]
Oh my god that is the most Windows thing that ever windowed.

I just put `avbin.dll` and `avbin64.dll` in both directories and it worked. I then removed the 32 from 32 and the 64 from 64 and it still worked.

I feel happy that it is working now, but *extremely* unsatisfied with what the problem was. Thanks for figuring this out.

**Comment by larsoner** [comment]
In theory since you are using 32-bit Python (for TDT right?) then you can remove the 64-bit library from `system32`, too :)

**Comment by drammock** [comment]
FWIW, I've heard reports that `avbin64.dll` simply doesn't work with pyglet, and that even on 64-bit systems with 64-bit python you have to use the 32-bit `avbin.dll`.  Just to make it a bit windowier (or pyglettier?)

**Comment by drammock** [comment]
also +100 to @larsoner for debugging and fixing this so fast, even though I'm the one who wrote most of the video playback code :shame:

**Comment by larsoner** [comment]
In my testing (and on AppVeyor) I used the `avbin64.dll` on 64-bit Python and it works. I think both are on 1.3.2

**Comment by drammock** [comment]
good to know.  I did get partway to setting up a W10 VPN today, so when I
get that fully operational I'll try that out here too.

**Comment by larsoner** [comment]
... now if only one or both of you could convert some of that appreciation into code review: #352 :)

**Comment by rkmaddox** [comment]
I am not sure I even know how to review a PR like this...

**Comment by rkmaddox** [comment]
Correction: I am sure I don't.
