### ISSUE TITLE
Incorrect frame rate

### ISSUE THREAD

**Issue by sjjoo** [LABSN/expyfun#356]
My monitor has 60 Hz refresh rate, but ec.estimate_screen_fs() returns 30 Hz.

On Linux Mint 17.3

**Comment by larsoner** [comment]
I seem to recall this being a problem a few years ago under Linux with some window managers. At the time, Xfce worked fine but Compiz-based WMs did not. Thus this comment:

https://github.com/LABSN/expyfun/blob/master/examples/sync/sync_test.py#L8

But I just tried `xfce` (Ubuntu 18.04, NVIDIA graphics) and still got 33 ms instead of 16.

**Comment by larsoner** [comment]
@drammock can you replicate this problem, too?

**Comment by drammock** [comment]
I think you can only get 16ms under pure xfce (not xubuntu, which puts
other stuff on top of xfce)?  I also get 33ms, but that's no surprise
because I run compiz.

**Comment by rkmaddox** [comment]
Yep, it has been an issue for a long time, but unless you are going to be running it on that computer I wouldn't worry about it.

Any visual stimulus code you write should depend the trial clock and not the frame number.

**Comment by larsoner** [comment]
Does the text / justification in #357 make sense?

**Comment by rkmaddox** [comment]
If the unsafe mode in #357 could lead to timing issues, then the experimenter needs to remember to change it back to safe for running on the experimental computer, which makes me nervous. I don't like the idea of having machine-dependent variables that need to be manually set.

Perhaps it should be a system-wide setting that defaults to safe if unspecified?

**Comment by drammock** [comment]
I like @rkmaddox's idea of adding this to the machine-specific `expyfun.json` variables. To be consistent with past practice though, it should probably also still be an arg that can be passed when initializing `ExperimentController` (just as `window_size`, `screen_num`, etc)

**Comment by larsoner** [comment]
> Perhaps it should be a system-wide setting that defaults to safe if unspecified?

>  it should probably also still be an arg that can be passed

Done
