### ISSUE TITLE
DIS: Use scipy.io.savemat rather than expyfun.io.write_hdf5?

### ISSUE THREAD

**Issue by rkmaddox** [LABSN/expyfun#363]
So MATLAB's .mat files are now basically hdf5 files, which are easy to read and write in both python and MATLAB. I have hit the situation where I generally use `expyfun`'s hdf5 format because it works and it's easy for me. But I have also now hit the situation where I want to share data with people, and my options are tell them to install `expyfun` or load the data and save to .mat file.

Is there something the output of our `write_hdf5` can handle that `savemat` cannot? If so I'd suggest we start to deprecate our in-house format. Obviously I can just stop using it, but I wanted to ask first if there was a compelling reason why I shouldn't.

**Comment by rkmaddox** [comment]
Actually I just noticed this in the 3.0.0 changelog:

> `read_hdf5` and `write_hdf5` are now part of external module `h5io`.

Does that mean I can just tell people to install that much smaller module? That is certainly better than making people install the whole of `expyfun` just to get at the data. I still do wonder what it offers over MATLAB though.

**Comment by larsoner** [comment]
Yes you can tell them to install h5io. Or MATLAB does have native H5 reading functionality. Try loading one of the h5io files in MATLAB yourself, hopefully you'll see it's easy enough to get to the numerical data.

The advantage of h5io is that it very easily reads and writes in built-in Python types plus some common numerical ones. You can write out a tuple of list of dict of numpy array and scipy CSR sparse matrices, and you get exactly that hierarchy back on read. So if you want to stay in Python it's very simple. And even in MATLAB, it should be easy to see how this hierarchy is constructed and traversed.

OTOH, write some data in H5 format with MATLAB and read it in Python and see what you get. It's ... less than beautiful. There has some effort to make this simpler, though, see pymatreader.

**Comment by rkmaddox** [comment]
I figured this was the answer. I did not realize that those files could be read into MATLAB! That is huge, thanks.

Closes #363.

**Comment by larsoner** [comment]
IIRC I tried and was able to read them at one point, but it was a while ago so I could be wrong. Make sure you try locally before suggesting to others it is possible :)

**Comment by larsoner** [comment]
(I would have tested myself before posting the suggestion, but my MATLAB license apparently has lapsed so I'll leave it to you)
