### ISSUE TITLE
ec.load_buffer() is slow

### ISSUE THREAD

**Issue by JustinTFleming** [LABSN/expyfun#407]
Loading a fairly large stimulus to the buffer (53 chans, 16 sec at 48kHz) is taking longer than expected: 6.93 sec, 7.04 sec, and 7.00 sec on three test runs.

Ross mentioned that this may be a known bug related to unnecessary memory copying.

**Comment by larsoner** [comment]
@JustinTFleming indeed, we can probably avoid this by being more careful about copies.
