### ISSUE TITLE
need to update install dependencies

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#414]
Might be nice to have a "quick-start" installation section that includes something like the following

```
$ conda create -n expy python=3 numpy scipy matplotlib pandas pyglet h5py joblib pillow
$ conda activate expy
$ pip install mne pyparallel rtmixer expyfun
```

**Comment by drammock** [comment]
(the missing dependency alluded to in the issue title is `pillow`)

**Comment by larsoner** [comment]
Can you add this to https://labsn.github.io/expyfun/getting_started.html#dependencies ?
