### ISSUE TITLE
TypeError: read_tab() got an unexpected keyword argument 'allow_last_missing'

### ISSUE THREAD

**Issue by ktavabi** [LABSN/expyfun#423]
> TypeError                                 Traceback (most recent call last)
> ~/Github/Projects/badbaby/badbaby/processing/mnefun_script.py in 
>      66     default = False
>      67     try:
> ---> 68         mnefun.do_processing(
>      69             params,
>      70             fetch_raw=default,
> 
> ~/Github/mnefun/mnefun/_mnefun.py in do_processing(p, fetch_raw, do_score, push_raw, do_sss, fetch_sss, do_ch_fix, gen_ssp, apply_ssp, write_epochs, gen_covs, gen_fwd, gen_inv, gen_report, print_status)
>     524                 outs[ii] = func(p, subjects, run_indices, decim)
>     525             else:
> --> 526                 outs[ii] = func(p, subjects, run_indices)
>     527             print('  (' + timestring(time.time() - t0) + ')')
>     528             if p.on_process is not None:
> 
> ~/Github/mnefun/mnefun/_mnefun.py in score_fun(p, subjects, run_indices)
>     439 
>     440         def score_fun(p, subjects, run_indices):
> --> 441             return score_fun_two(p, subjects)
>     442     funcs = [fetch_raw_files,
>     443              score_fun,
> 
> ~/Github/Projects/badbaby/badbaby/processing/score.py in score(p, subjects)
>      94             assert sum(good) == 1, sum(good)
>      95             fname_tab = tab_files[np.where(good)[0][0]]
> ---> 96             data = read_tab(fname_tab, allow_last_missing=True)
>      97 
>      98             # Correct the triggers
>

**Comment by larsoner** [comment]
Are you up to date? This should work if you're newer than Dec 18th

https://github.com/LABSN/expyfun/pull/422
