### ISSUE TITLE
FIX: Expyfun package requirements

### ISSUE THREAD

**Issue by NeuroLaunch** [LABSN/expyfun#431]
When updating the UW lab's expyfun environment I ran into an issue where a pyglet method was not found.  Specifically, `.glMatrixMode` was not recognized during a call to `exp_controller_module`.   Apparently the issue arises from changes in pyglet's support of OpenGL, whereby glMatrixMode and other methods have been deprecated.

@drammock has suggested specifying pyglet < 2.0 in the package setup (I had success downgrading to pyglet 1.5.18) or updating expyfun to support the recent versions of pyglet and OpenGL.

**Comment by larsoner** [comment]
The current stable release is 1.5.18, and indeed 2.0-flavor (which are currently in prerelease phase) are not supported. We'll have to refactor drawing once 2.0.0 is actually released.

**Comment by NeuroLaunch** [comment]
Sorry, I may have jumped the gun then.  I had run a 'conda update conda',
which may have changed the pyglet version; alternatively, I see our stim
computer has a clone of the pyglet repo so the 2.0 version may have been
pulled in.  (I'm still getting used to the expyfun coding environment.)

**Comment by larsoner** [comment]
If using the pyglet repo you want to be on the 1.5-maintenance branch, not main/master (which has 2.0-dev)

**Comment by larsoner** [comment]
@NeuroLaunch can you make a PR to update https://github.com/LABSN/expyfun/blob/main/doc/getting_started.rst to tell people to use `pyglet-1.5-maintenance` rather than `master` if they're going that route? This also got @JustinTFleming recently

**Comment by NeuroLaunch** [comment]
@larsoner Yes, I can do that.
