### ISSUE TITLE
cannot pip install expyfun

### ISSUE THREAD

**Issue by drammock** [LABSN/expyfun#434]
- https://pypi.org/project/expyfun/ is currently a 404
- searching https://pypi.org/search/?q=expyfun yields no results
- `pip install expyfun` yields `ERROR: Could not find a version that satisfies the requirement expyfun (from versions: none) ERROR: No matching distribution found for expyfun`

**Comment by drammock** [comment]
(I should add that other packages on pip are fine, e.g., [pyparallel](https://pypi.org/project/pyparallel/)

**Comment by larsoner** [comment]
Oh yeah, I guess we have never actually released on PyPi. We should probably update those instructions to just use the GitHub URL

**Comment by drammock** [comment]
I'll update the instructions now
